In [3]:
!pip install numpy

In [5]:
!pip install numpy --upgrade

  Using cached https://files.pythonhosted.org/packages/a9/38/f6d6d8635d496d6b4ed5d8ca4b9f193d0edc59999c3a63779cbc38aa650f/numpy-1.18.1-cp37-cp37m-win_amd64.whl
  Found existing installation: numpy 1.16.5
    Uninstalling numpy-1.16.5:


ERROR: Could not install packages due to an EnvironmentError: [WinError 5] Access is denied: 'c:\\programdata\\anaconda3\\lib\\site-packages\\numpy\\compat\\py3k.py'
Consider using the `--user` option or check the permissions.



In [6]:
!pip install numpy --user

In [7]:
!pip install numpy --upgrade

  Using cached https://files.pythonhosted.org/packages/a9/38/f6d6d8635d496d6b4ed5d8ca4b9f193d0edc59999c3a63779cbc38aa650f/numpy-1.18.1-cp37-cp37m-win_amd64.whl
  Found existing installation: numpy 1.16.5
    Uninstalling numpy-1.16.5:


ERROR: Could not install packages due to an EnvironmentError: [WinError 5] Access is denied: 'c:\\programdata\\anaconda3\\lib\\site-packages\\numpy\\compat\\py3k.py'
Consider using the `--user` option or check the permissions.



In [8]:
!pip install numpy --upgrade --user

  Using cached https://files.pythonhosted.org/packages/a9/38/f6d6d8635d496d6b4ed5d8ca4b9f193d0edc59999c3a63779cbc38aa650f/numpy-1.18.1-cp37-cp37m-win_amd64.whl


  Consider adding this directory to PATH or, if you prefer to suppress this warning, use --no-warn-script-location.


In [9]:
import numpy as np #------as is used to alias names

In [10]:
array_one = np.array([1,2,3,4])

array_one

array([1, 2, 3, 4])

In [11]:
type(array_one)

numpy.ndarray

In [12]:
numbers = [9,8,7,6]

array_two = np.array(numbers)

array_two

array([9, 8, 7, 6])

In [14]:
array_of_zeroes = np.zeros((3,4))

array_of_zeroes

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [15]:
array_of_ones = np.ones((3,4))

array_of_ones

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
array_of_ones_int = np.ones((3,4),dtype=np.int16)

array_of_ones_int

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]], dtype=int16)