In [2]:
import numpy as np

In [3]:
np.arange(2,31,2)

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30])

In [6]:
e = np.array([(1,2,3),(4,5,6),(7,8,9)])

e

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [7]:
e.shape

(3, 3)

In [8]:
x = np.arange(1,15)

x

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [9]:
x.shape

(14,)

In [10]:
y = np.arange(1,9)

y

array([1, 2, 3, 4, 5, 6, 7, 8])

In [11]:
y.shape

(8,)

In [12]:
y = np.arange(1,9).reshape(2,4)

y

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [13]:
y.shape

(2, 4)

In [21]:
y = np.arange(1,15).reshape(7,2)

y

array([[ 1,  2],
       [ 3,  4],
       [ 5,  6],
       [ 7,  8],
       [ 9, 10],
       [11, 12],
       [13, 14]])

In [22]:
y.shape

(7, 2)