In [1]:
#indexing and slicing of an array:

In [2]:
import numpy as np

In [4]:
a = np.arange(11)**2

a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [5]:
#indexing:

In [6]:
a[2]

4

In [7]:
# negative indexing

a[-4]

49

In [8]:
#slicing an array

In [9]:
a[3:8]

array([ 9, 16, 25, 36, 49], dtype=int32)

In [12]:
#step count

a[2:10:2]

array([ 4, 16, 36, 64], dtype=int32)

In [13]:
#reversing an array

a[::-1]

array([100,  81,  64,  49,  36,  25,  16,   9,   4,   1,   0], dtype=int32)

In [14]:
a[:8]

array([ 0,  1,  4,  9, 16, 25, 36, 49], dtype=int32)

In [15]:
a[2:]

array([  4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [16]:
#Mix of data types:

In [17]:
students = np.array([['John','Sam','Whitney','Rose'],
                    [15,25,30,45],
                    [20,25,35,26]])

students

array([['John', 'Sam', 'Whitney', 'Rose'],
       ['15', '25', '30', '45'],
       ['20', '25', '35', '26']], dtype='<U7')

In [18]:
type(students)

numpy.ndarray

In [19]:
students[0]

array(['John', 'Sam', 'Whitney', 'Rose'], dtype='<U7')

In [20]:
students[1]

array(['15', '25', '30', '45'], dtype='<U7')

In [21]:
students[2]

array(['20', '25', '35', '26'], dtype='<U7')

In [22]:
students[0:1]

array([['John', 'Sam', 'Whitney', 'Rose']], dtype='<U7')

In [31]:
students[0:2,2:4]

array([['Whitney', 'Rose'],
       ['30', '45']], dtype='<U7')

In [32]:
students[0:3,1:4]

array([['Sam', 'Whitney', 'Rose'],
       ['25', '30', '45'],
       ['25', '35', '26']], dtype='<U7')

In [33]:
#iterating over arrays:

students_list = np.array([['John','Sam','Whitney','Rose'],
                    [15,25,30,45],
                    [20,25,35,26]])

students_list

array([['John', 'Sam', 'Whitney', 'Rose'],
       ['15', '25', '30', '45'],
       ['20', '25', '35', '26']], dtype='<U7')

In [35]:
for i in students_list:
    print('i = ',i)

i =  ['John' 'Sam' 'Whitney' 'Rose']
i =  ['15' '25' '30' '45']
i =  ['20' '25' '35' '26']


In [36]:
a = np.arange(11)**2

a

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100], dtype=int32)

In [37]:
for i in a:
    print(i**(1/2))

0.0
1.0
2.0
3.0
4.0
5.0
6.0
7.0
8.0
9.0
10.0


In [40]:
for element in students_list.flatten():
    print(element) #Row major flattening
    

John
Sam
Whitney
Rose
15
25
30
45
20
25
35
26


In [42]:
for element in students_list.flatten(order = 'F'):
    print(element) #column major flattening

John
15
20
Sam
25
25
Whitney
30
35
Rose
45
26


In [43]:
x = np.arange(12).reshape(4,3)

x

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [45]:
for i in np.nditer(x):
    print(i) #Row major flattening

0
1
2
3
4
5
6
7
8
9
10
11


In [46]:
for i in np.nditer(x, order = 'F'):
    print(i) #Column major flattening

0
3
6
9
1
4
7
10
2
5
8
11
