In [2]:
import numpy as np

In [5]:
angles = np.array([0,30,40,60,90])

In [9]:
angle_radians = angles*np.pi/180

angle_radians


array([0.        , 0.52359878, 0.6981317 , 1.04719755, 1.57079633])

In [11]:
angles_radians = np.radians(angles)

angles_radians

array([0.        , 0.52359878, 0.6981317 , 1.04719755, 1.57079633])

In [12]:
print('sine of the angles in the array')

print(np.sin(angle_radians))

sine of the angles in the array
[0.         0.5        0.64278761 0.8660254  1.        ]


In [13]:
#statistical functions of numpy

In [14]:
test_scores = np.array([32.5,56.9,58.25,48.35,98.65,83.45])

In [15]:
print('Mean test score of the students:')

print(np.mean(test_scores))

Mean test score of the students:
63.01666666666666


In [16]:
print('Median of test scores of the students:')

print(np.median(test_scores))

Median of test scores of the students:
57.575


In [18]:
#arithmetic operations of numpy

a = np.array([20,20,20])
b = np.array([5,5,4])

In [19]:
a+b

array([25, 25, 24])

In [20]:
a-b

array([15, 15, 16])

In [21]:
a*b

array([100, 100,  80])

In [22]:
a/b

array([4., 4., 5.])

In [23]:
a**b

array([3200000, 3200000,  160000], dtype=int32)

In [24]:
a<b

array([False, False, False])

In [25]:
a>b

array([ True,  True,  True])

In [26]:
a==b

array([False, False, False])

In [27]:
a!=b

array([ True,  True,  True])

In [28]:
#numpy unary operators

In [29]:
ages = np.array([12,15,18,20])

In [31]:
ages.sum()

65

In [32]:
ages.min()

12

In [33]:
ages.max()

20

In [34]:
numbers = np.arange(12).reshape(3,4)

numbers

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [35]:
numbers.sum(axis=0)

array([12, 15, 18, 21])

In [36]:
numbers.sum(axis = 1)

array([ 6, 22, 38])